version: "3.8"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=ctfm
      - POSTGRES_USER=ctfm
      - POSTGRES_PASSWORD=ctfm
    expose: 
      - 5432
    ports:
      - "28432:5432"
  redis:
    image: redis
    command: redis-server --requirepass redispassword
    expose:
        - 6379
  ctfm:
    image: ctfm
    build: "."
    volumes:
      - .:/backend
    restart: always
    ports:
      - "28082:8086"
    environment: 
      - SECRET_KEY="Test"
    depends_on:
      - migration
      - db
      - redis