version: "3.6"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=ctfm
      - POSTGRES_USER=ctfm
      - POSTGRES_PASSWORD=/run/secrets/ctfm_db_password
    expose:
      - 5432
    ports:
      - "28432:5432"
    networks:
      internal:
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis
    environment:
      - REDIS_PASS_FILE=/run/secrets/ctfm_redis_password
    command: [
      "bash", "-c",
      '
       docker-entrypoint.sh
       --requirepass "$$(cat $$REDIS_PASS_FILE)"
      '
    ]
    expose:
      - 6379
    restart: always
    networks:
      internal:
  ctfm:
    image: ctfm
    build: 
      context: "./backend"
    user: root
    secrets:
      - ctfm_redis_password
      - ctfm_db_password
      - ctfm_secret_key
    volumes:
      - ./backend:/backend
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    expose:
      - "8086"
      - "8087"
    environment:
      - SECRET_KEY_FILE=/run/secrets/ctfm_secret_key
      - DB_PASSWORD_FILE=/run/secrets/ctfm_db_password
      - DB_USER=ctfm
      - REDIS_PASSWORD_FILE=/run/secrets/ctfm_redis_password
    depends_on:
      - db
      - redis
    networks:
      internal:
      frp:
        ipv4_address: 172.1.0.2
  frpc:
    image: ctfm/frp
    restart: always
    volumes:
      - ./frp:/conf/
    depends_on:
      - frps
    entrypoint:
      - /usr/local/bin/frpc
      - -c
      - /conf/frpc.ini
    tty:
      true
    networks:
      frp:
        ipv4_address: 172.1.0.3
      frp_containers:

  frps:
    image: ctfm/frp
    build:
      context: "./frp"
    restart: always
    volumes:
      - ./frp:/conf/
    entrypoint:
      - /usr/local/bin/frps
      - -c
      - /conf/frps.ini
    network_mode: host

networks:
  default:
  internal:
    internal: true
  frp:
    driver: bridge
    ipam:
      config:
        - subnet: 172.1.0.0/16
  frp_containers:
    driver: overlay
    internal: true
    ipam:
      config:
        - subnet: 172.2.0.0/16
