# Generated by Django 3.1.3 on 2020-12-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=256)),
                ('content', models.TextField(default='')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
