# Generated by Django 3.1.3 on 2020-12-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type_icon',
            field=models.CharField(default='', max_length=48),
        ),
    ]
