# Generated by Django 3.1.5 on 2021-02-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_contest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='have_school_ranking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='school_email_suffixes',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
