# Generated by Django 4.0.2 on 2022-03-03 16:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenge', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeDocker',
            fields=[
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='challenge.challenge')),
                ('protocol', models.IntegerField(choices=[(1, 'TCP'), (2, 'HTTP')], default=1)),
                ('image', models.CharField(max_length=512)),
                ('redirect_port', models.IntegerField()),
                ('memory_limit', models.CharField(default='128m', max_length=64)),
                ('cpu_limit', models.FloatField(default=0.5)),
            ],
        ),
        migrations.CreateModel(
            name='WhaleConfig',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeContainer',
            fields=[
                ('start_time', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('renew_count', models.IntegerField(default=0, null=True)),
                ('status', models.IntegerField(default=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('port', models.IntegerField(default=0, null=True)),
                ('flag', models.CharField(default='', max_length=512)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
