# Generated by Django 4.0.3 on 2022-03-22 04:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhaleConfig',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeContainer',
            fields=[
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('renew_count', models.IntegerField(default=0, null=True)),
                ('status', models.IntegerField(default=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('port', models.IntegerField(default=0, null=True)),
                ('flag', models.CharField(default='', max_length=512)),
                ('host', models.CharField(default='', max_length=512, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge')),
            ],
        ),
    ]
