# Generated by Django 4.0.2 on 2022-03-05 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChallengeDocker',
        ),
    ]
