# Generated by Django 4.0.3 on 2022-03-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0002_delete_challengedocker'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='challengecontainer',
            constraint=models.UniqueConstraint(fields=('user', 'challenge'), name='unique_attention'),
        ),
    ]
