# Generated by Django 4.0.3 on 2022-03-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0003_challengecontainer_unique_attention'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengecontainer',
            name='address',
            field=models.CharField(default='', max_length=512),
        ),
    ]
