# Generated by Django 3.1.3 on 2020-11-30 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=256)),
                ('content', models.TextField(default='')),
                ('author', models.CharField(default='', max_length=256)),
                ('summary', models.CharField(default='', max_length=256)),
                ('difficulty', models.IntegerField(default=0)),
                ('points', models.BigIntegerField(default=0)),
                ('solved_amount', models.BigIntegerField(default=0)),
                ('flag', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(max_length=512)),
                ('icon', models.CharField(default='', max_length=256)),
                ('challenge_amount', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolutionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
