# Generated by Django 4.0.3 on 2022-03-22 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutiondetail',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.team'),
        ),
    ]
