# Generated by Django 3.1.3 on 2020-12-01 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20201130_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengecategory',
            name='challenge_amount',
        ),
    ]
