# Generated by Django 3.1.5 on 2021-01-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20210120_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='attachment_url',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='have_dynamic_container',
            field=models.BooleanField(default=False),
        ),
    ]
