# Generated by Django 3.1.5 on 2021-02-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_auto_20210125_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestuser',
            name='attempted_challenges',
            field=models.ManyToManyField(through='challenge.SolutionDetail', to='challenge.Challenge'),
        ),
    ]
