# Generated by Django 4.0.2 on 2022-03-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='have_dynamic_container',
            new_name='has_dynamic_container',
        ),
        migrations.AddField(
            model_name='challenge',
            name='cpu_limit',
            field=models.FloatField(default=0.5, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='image',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='memory_limit',
            field=models.CharField(default='128m', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='protocol',
            field=models.IntegerField(choices=[(1, 'TCP'), (2, 'HTTP')], default=1),
        ),
        migrations.AddField(
            model_name='challenge',
            name='redirect_port',
            field=models.IntegerField(null=True),
        ),
    ]
