# Generated by Django 3.1.3 on 2020-12-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20201202_0035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='points',
            new_name='initial_points',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='solved_amount',
        ),
        migrations.AddField(
            model_name='challenge',
            name='decay',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='minimum_points',
            field=models.BigIntegerField(default=0),
        ),
    ]
