# Generated by Django 3.1.5 on 2021-02-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210120_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
